### ISSUE TITLE
Cannot find a resource matching service[redis6379]

### ISSUE THREAD

**Issue by runningman84** [portertech/chef-monitor#28]
The monitor master recipe doesn't work even if I try to put sensu::redis in front of it.

```
Starting Chef Client, version 11.16.2
resolving cookbooks for run list: ["sensu::redis", "sensu::rabbitmq", "monitor::master"]
Synchronizing Cookbooks:
  - apt
  - sensu
  - yum
  - chef_handler
  - windows
  - rabbitmq
  - yum-erlang_solutions
  - erlang
  - yum-epel
  - build-essential
  - redisio
  - ulimit
  - sudo
  - monitor
Compiling Cookbooks...

================================================================================
Recipe Compile Error in /var/chef/cache/cookbooks/sensu/recipes/redis.rb
================================================================================

Chef::Exceptions::ResourceNotFound
----------------------------------
Cannot find a resource matching service[redis6379] (did you define it first?)

Cookbook Trace:
---------------
  /var/chef/cache/cookbooks/redisio/recipes/enable.rb:25:in `block in from_file'
  /var/chef/cache/cookbooks/redisio/recipes/enable.rb:23:in `each'
  /var/chef/cache/cookbooks/redisio/recipes/enable.rb:23:in `from_file'
  /var/chef/cache/cookbooks/sensu/recipes/redis.rb:23:in `from_file'

Relevant File Content:
----------------------
/var/chef/cache/cookbooks/redisio/recipes/enable.rb:

 18:  # limitations under the License.
 19:  #
 20:  
 21:  redis = node['redisio']
 22:  
 23:  redis['servers'].each do |current_server|
 24:    server_name = current_server["name"] || current_server["port"]
 25>>   resource = resources("service[redis#{server_name}]")
 26:    resource.action Array(resource.action)
 27:    resource.action << :start
 28:    resource.action << :enable
 29:  end
 30:  


Running handlers:
[2014-09-23T14:43:43+00:00] ERROR: Running exception handlers
Running handlers complete
[2014-09-23T14:43:43+00:00] ERROR: Exception handlers complete
[2014-09-23T14:43:43+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated in 5.382873795 seconds
[2014-09-23T14:43:43+00:00] ERROR: Cannot find a resource matching service[redis6379] (did you define it first?)
[2014-09-23T14:43:44+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

**Comment by danrex** [comment]
This seems to be an issue with the 2.x version of the redisio cookbook. Version 1.7.1 seems to work fine.
